### ISSUE TITLE
default plot

### ISSUE THREAD

**Issue by pfistfl** [mmostly-harmless/ggparty#10]
I think it would be really important to have a `autoplot` function, i.e. 
somewhat intelligently chosen defaults. 

This could look like this for the `lmtree`:

```r
data("TeachingRatings", package = "AER")
tr <- subset(TeachingRatings, credits == "more")

tr_tree <- lmtree(eval ~ beauty | minority + age + gender + division + native +
                    tenure, data = tr, weights = students, caseweights = FALSE)

autoplot(tr_tree,  col = tenure, shape = minority)
```
where `col` and `shape` default to the first elements in the formula, i.e. minority and age. 
(We could also leave col and shape out for now)

The resulting figure should be the same as the one in the README

**Comment by pfistfl** [comment]
Or also as an analogy to `ggplot` just call it `qplot()` ?

**Comment by martin-borkovec** [comment]
i think autoplot would be the better option. Will be implemented

**Comment by pfistfl** [comment]
This is actually a thing: 
https://www.rdocumentation.org/packages/ggplot2/versions/3.1.0/topics/autoplot
