### ISSUE TITLE
naming scheme

### ISSUE THREAD

**Issue by martin-borkovec** [mmostly-harmless/ggparty#19]
I'm about to rework geom_node_info and geom_node_splitvar and to merge them into one geom that I'd call something like geom_node_text or geom_nodetext.

Considering the names of geom_nodeplot and geom_edge_label there seems to be little consitency in the naming of the functions up until now, so I'm thinking about which naming scheme to pick and renaming the respective ones.

Any opinions?

**Comment by Niyazu** [comment]
Personally would stick to underscores for slightly better readability reasons.
So in this case I would go for geom_node_text and maybe rename geom_nodeplot to geom_node_plot.
